name: Build PioneOS

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - run: sudo apt update
    
    - run: sudo apt upgrade -y

    - run: sudo apt install -y debootstrap genisoimage syslinux-utils squashfs-tools zsync expect

    - run: ./build-iso --user-default defaults

    - uses: actions/upload-artifact@v4
      with:
        name: PioneOS_build
        path: Remaster/iso-files/*.iso
