name: Build PioneOS

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    container:
      image: 777shuang/build-pioneos

    steps:
    - uses: actions/checkout@v4

    - run: ./build-iso --user-default defaults

    - uses: actions/upload-artifact@v4
      with:
        name: PioneOS_build
        path: Remaster/iso-files/*.iso
